name: Watering the plants on GitHub

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Water and commit
        run: |
          date_now=$(date '+%Y-%m-%d %H:%M:%S')
          echo "🌱 Plant watered: $date_now" >> 🌱.txt

          git add 🌱.txt
          git commit -m "🌿 Plant watered: $date_now"
          git pull origin main --rebase 
          git push origin main
