name: Watering the plants on GitHub

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout plant
        run: |
          git clone https://github.com/$GITHUB_REPOSITORY.git .
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      - name: Water and commit
        run: |
          date_now=$(date '+%Y-%m-%d %H:%M:%S')
          echo "🌱 Plant watered: $date_now" >> 🌱.txt

          git add 🌱.txt
          git commit -m "🌿 Plant watered: $date_now"
          git pull origin main --rebase 
          git push origin main
